consul:
  image: consul:v0.6.4
  user: consul
  volumes:
    - ./files/consul.json:/etc/consul.json
  ports:
    - 8500:8500
  environment:
    - "GOMAXPROCS=2"
  command: "consul agent -config-file=/etc/consul.json"

mariadb:
  image: tyuvil/alpine-mariadb:v10.1.14
  environment:
    - "MYSQL_ROOT_PASSWORD=secret"
  ports:
    - 3306:3306

vault:
  image: vault:v0.6.0
  user: vault
  volumes:
    - ./files/vault.hcl:/etc/vault.hcl
  links:
    - "consul:consul"
    - "mariadb:mariadb"
  ports:
    - 8200:8200
  environment:
    - "GOMAXPROCS=2"
  command: "vault server -config=/etc/vault.hcl"
