mysql:
  image: mysql:5.7
  environment:
    - "MYSQL_ROOT_PASSWORD=secret"
  ports:
    - 3306:3306

consul:
  #build: .
  image: tyauvil/alipine-vault-consul:latest
  user: consul
  volumes:
    - ./files/consul.json:/etc/consul.json
  ports:
    - 8500:8500
  environment:
    - "GOMAXPROCS=2"
  command: "consul agent -config-file=/etc/consul.json"

vault:
  #build: .
  image: tyauvil/alipine-vault-consul:latest
  user: vault
  volumes:
    - ./files/vault.hcl:/etc/vault.hcl
  links:
    - "consul:consul"
    - "mysql:mysql"
  ports:
    - 8200:8200
  environment:
    - "GOMAXPROCS=2"
  command: "vault server -config=/etc/vault.hcl"
